### ISSUE TITLE
Synchronization Between CoppeliaSim and Simulink

### ISSUE THREAD

**Issue by ZPHuang-ACM** [santdiego/simExtSimulink#2]
Thank you for creating this work！

I wonder whether there is a synchronization between Simulink and CoppeliaSim? 

In other words, are the simulation steps in CoppeliaSim triggered by Simulink? or they are totally independent? 

Thank you!

**Comment by yu-zy11** [comment]
sorry.I always use CoppeliaSim with matlab

发自我的iPhone

**Comment by santdiego** [comment]
> Thank you for creating this work！
> 
> I wonder whether there is a synchronization between Simulink and CoppeliaSim?
> 
> In other words, are the simulation steps in CoppeliaSim triggered by Simulink? or they are totally independent?
> 
> Thank you!


Hello . Thanks for your interest.
In answer to your question, no, at the moment the simulink-coppeliasim steps are not synchronized. Although this could be implemented by script, it would be more practical and easier to add the functionality to the blocks. It is in my plans to implement this in the near future. In any case, the synchronization should be done from the simulink clock, since altering the simulation steps is easier (and less problematic) in CoppeliaSim than in simulink.
Greetings!

**Comment by ZPHuang-ACM** [comment]
Thank you for clarifying it for me!
